base:
  project: Online-Shoppers-Intention
  random-state: 42
  target_col: Revenue

data_source:
  s3_source: data_given/online_shoppers_intention.csv

load_data:
  raw_dataset_csv: data/raw/online_shoppers_intention.csv

preprocess_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2


model_dir: saved_models